# Generated by Django 2.2.7 on 2023-04-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20230412_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalproduct',
            name='product_img1',
            field=models.ImageField(blank=True, default='https://media.istockphoto.com/id/1295274245/photo/random-multicolored-spheres-computer-generated-abstract-form-of-large-and-small-balls-3d.jpg?b=1&s=170667a&w=0&k=20&c=On1rcMZtCPflzFJP6Wc2Y5GiRy0w0j1RA52FH-0EUX0=', max_length=10000, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='generalproduct',
            name='product_img2',
            field=models.ImageField(blank=True, default='https://media.istockphoto.com/id/1295274245/photo/random-multicolored-spheres-computer-generated-abstract-form-of-large-and-small-balls-3d.jpg?b=1&s=170667a&w=0&k=20&c=On1rcMZtCPflzFJP6Wc2Y5GiRy0w0j1RA52FH-0EUX0=', max_length=10000, null=True, upload_to='products/'),
        ),
    ]
